server:
  port: 9090
  error:
    include-message: always


spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  jpa:
    database: SQL_SERVER
    show-sql: true
    hibernate:
      ddl-auto: update   # en prod evita create-drop
  datasource:
    #url: jdbc:sqlserver://192.168.1.16:1433;database=sqlprestamos;trustServerCertificate=true;loginTimeout=30;
    url: jdbc:sqlserver://slqproyectoumg.database.windows.net;database=empe√±oDB;trustServerCertificate=true;loginTimeout=30;
    #username: admin
    username: sqladmin@slqproyectoumg
    #password: admin
    password: Sqlumg2025
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    webmvc:
      cors:
        allowed-origins: "http://localhost:3000"